// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: influxdata/iox/management/v1/parse_delete.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operators supported in delete binary expressions
type DeleteOp int32

const (
	// not specified
	DeleteOp_DELETE_OP_UNSPECIFIED DeleteOp = 0
	// "="
	DeleteOp_DELETE_OP_EQ DeleteOp = 1
	// "!="
	DeleteOp_DELETE_OP_NOT_EQ DeleteOp = 2
)

// Enum value maps for DeleteOp.
var (
	DeleteOp_name = map[int32]string{
		0: "DELETE_OP_UNSPECIFIED",
		1: "DELETE_OP_EQ",
		2: "DELETE_OP_NOT_EQ",
	}
	DeleteOp_value = map[string]int32{
		"DELETE_OP_UNSPECIFIED": 0,
		"DELETE_OP_EQ":          1,
		"DELETE_OP_NOT_EQ":      2,
	}
)

func (x DeleteOp) Enum() *DeleteOp {
	p := new(DeleteOp)
	*p = x
	return p
}

func (x DeleteOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteOp) Descriptor() protoreflect.EnumDescriptor {
	return file_influxdata_iox_management_v1_parse_delete_proto_enumTypes[0].Descriptor()
}

func (DeleteOp) Type() protoreflect.EnumType {
	return &file_influxdata_iox_management_v1_parse_delete_proto_enumTypes[0]
}

func (x DeleteOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteOp.Descriptor instead.
func (DeleteOp) EnumDescriptor() ([]byte, []int) {
	return file_influxdata_iox_management_v1_parse_delete_proto_rawDescGZIP(), []int{0}
}

// a delete binary expression is either 'column_name = constant'
// or 'column_name != constant'
type DeleteBinaryExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Left hand side which is a column name
	Column string `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	// Operator
	Op DeleteOp `protobuf:"varint,2,opt,name=op,proto3,enum=influxdata.iox.management.v1.DeleteOp" json:"op,omitempty"`
	// Right hand side which is literal/constant
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DeleteBinaryExpr) Reset() {
	*x = DeleteBinaryExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_influxdata_iox_management_v1_parse_delete_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBinaryExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBinaryExpr) ProtoMessage() {}

func (x *DeleteBinaryExpr) ProtoReflect() protoreflect.Message {
	mi := &file_influxdata_iox_management_v1_parse_delete_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBinaryExpr.ProtoReflect.Descriptor instead.
func (*DeleteBinaryExpr) Descriptor() ([]byte, []int) {
	return file_influxdata_iox_management_v1_parse_delete_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteBinaryExpr) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *DeleteBinaryExpr) GetOp() DeleteOp {
	if x != nil {
		return x.Op
	}
	return DeleteOp_DELETE_OP_UNSPECIFIED
}

func (x *DeleteBinaryExpr) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// A description of a delete predicate
type ParseDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// start time in nanosecond of a range to be deleted
	StartTime int64 `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// stop time in nanosecodn of a range to be deleted
	StopTime int64 `protobuf:"varint,2,opt,name=stop_time,json=stopTime,proto3" json:"stop_time,omitempty"`
	// list of delete predicate binary expressions
	Exprs []*DeleteBinaryExpr `protobuf:"bytes,3,rep,name=exprs,proto3" json:"exprs,omitempty"`
}

func (x *ParseDelete) Reset() {
	*x = ParseDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_influxdata_iox_management_v1_parse_delete_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDelete) ProtoMessage() {}

func (x *ParseDelete) ProtoReflect() protoreflect.Message {
	mi := &file_influxdata_iox_management_v1_parse_delete_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDelete.ProtoReflect.Descriptor instead.
func (*ParseDelete) Descriptor() ([]byte, []int) {
	return file_influxdata_iox_management_v1_parse_delete_proto_rawDescGZIP(), []int{1}
}

func (x *ParseDelete) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ParseDelete) GetStopTime() int64 {
	if x != nil {
		return x.StopTime
	}
	return 0
}

func (x *ParseDelete) GetExprs() []*DeleteBinaryExpr {
	if x != nil {
		return x.Exprs
	}
	return nil
}

var File_influxdata_iox_management_v1_parse_delete_proto protoreflect.FileDescriptor

var file_influxdata_iox_management_v1_parse_delete_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x69, 0x6e, 0x66, 0x6c, 0x75, 0x78, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x69, 0x6f, 0x78,
	0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x61, 0x72, 0x73, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1c, 0x69, 0x6e, 0x66, 0x6c, 0x75, 0x78, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6f,
	0x78, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x22,
	0x78, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x45,
	0x78, 0x70, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x36, 0x0a, 0x02, 0x6f,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x69, 0x6e, 0x66, 0x6c, 0x75, 0x78,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6f, 0x78, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x70, 0x52,
	0x02, 0x6f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0b, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x70,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x6f,
	0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x05, 0x65, 0x78, 0x70, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x69, 0x6e, 0x66, 0x6c, 0x75, 0x78, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x69, 0x6f, 0x78, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x45, 0x78, 0x70, 0x72, 0x52, 0x05, 0x65, 0x78, 0x70, 0x72, 0x73, 0x2a, 0x4d, 0x0a, 0x08, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x70, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x5f, 0x4f, 0x50, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x5f,
	0x45, 0x51, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x4f,
	0x50, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x51, 0x10, 0x02, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x6c, 0x75, 0x78, 0x64,
	0x61, 0x74, 0x61, 0x2f, 0x69, 0x6f, 0x78, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_influxdata_iox_management_v1_parse_delete_proto_rawDescOnce sync.Once
	file_influxdata_iox_management_v1_parse_delete_proto_rawDescData = file_influxdata_iox_management_v1_parse_delete_proto_rawDesc
)

func file_influxdata_iox_management_v1_parse_delete_proto_rawDescGZIP() []byte {
	file_influxdata_iox_management_v1_parse_delete_proto_rawDescOnce.Do(func() {
		file_influxdata_iox_management_v1_parse_delete_proto_rawDescData = protoimpl.X.CompressGZIP(file_influxdata_iox_management_v1_parse_delete_proto_rawDescData)
	})
	return file_influxdata_iox_management_v1_parse_delete_proto_rawDescData
}

var file_influxdata_iox_management_v1_parse_delete_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_influxdata_iox_management_v1_parse_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_influxdata_iox_management_v1_parse_delete_proto_goTypes = []interface{}{
	(DeleteOp)(0),            // 0: influxdata.iox.management.v1.DeleteOp
	(*DeleteBinaryExpr)(nil), // 1: influxdata.iox.management.v1.DeleteBinaryExpr
	(*ParseDelete)(nil),      // 2: influxdata.iox.management.v1.ParseDelete
}
var file_influxdata_iox_management_v1_parse_delete_proto_depIdxs = []int32{
	0, // 0: influxdata.iox.management.v1.DeleteBinaryExpr.op:type_name -> influxdata.iox.management.v1.DeleteOp
	1, // 1: influxdata.iox.management.v1.ParseDelete.exprs:type_name -> influxdata.iox.management.v1.DeleteBinaryExpr
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_influxdata_iox_management_v1_parse_delete_proto_init() }
func file_influxdata_iox_management_v1_parse_delete_proto_init() {
	if File_influxdata_iox_management_v1_parse_delete_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_influxdata_iox_management_v1_parse_delete_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBinaryExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_influxdata_iox_management_v1_parse_delete_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_influxdata_iox_management_v1_parse_delete_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_influxdata_iox_management_v1_parse_delete_proto_goTypes,
		DependencyIndexes: file_influxdata_iox_management_v1_parse_delete_proto_depIdxs,
		EnumInfos:         file_influxdata_iox_management_v1_parse_delete_proto_enumTypes,
		MessageInfos:      file_influxdata_iox_management_v1_parse_delete_proto_msgTypes,
	}.Build()
	File_influxdata_iox_management_v1_parse_delete_proto = out.File
	file_influxdata_iox_management_v1_parse_delete_proto_rawDesc = nil
	file_influxdata_iox_management_v1_parse_delete_proto_goTypes = nil
	file_influxdata_iox_management_v1_parse_delete_proto_depIdxs = nil
}
